import turtle
from time import *
an=turtle.Screen()
a=turtle.Turtle()
an.bgcolor("violet")
a.shape("turtle")
a.color("green")
an.title("breath Test")
a.pensize(10)
a.penup()
a.right(90)
a.fd(270)
sleep(2)
style = ('Times new roman',15,'bold')
a.write("Start Inhaling",font=style,align="center")
a.hideturtle()
a.bk(30)
a.speed(3)
a.left(90)
a.pendown()
a.circle(250,180)
an.bgcolor("light green")
a.hideturtle()
a.penup()
a.left(90)
a.fd(200)
a.speed(10)
a.color("light yellow")
a.write("hold breadth",font=style,align="center")
a.color("red")
a.speed(3)
a.bk(200)
a.right(90)
a.pendown()
a.speed(10)
a.showturtle()
a.circle(250,180)
an.bgcolor("light blue")
a.color("violet")
a.circle(250)
an.bgcolor("light yellow")
a.left(90)
a.penup()
a.hideturtle
a.fd(200)
a.color("green")
a.write("exhale breath",font=style,align="center")
a.bk(200)
a.right(90)
a.pendown()
a.showturtle
a.circle(250,180)
